-- NoStock — schema (PostgreSQL)
-- Uso: psql "$DATABASE_URL" -f db/schema.sql
-- Nao editar depois de aplicado: mudanca de schema entra como migracao em db/migrations/.

-- ─────────────────────────────────────────────────────────────────── extensoes

create extension if not exists unaccent with schema extensions;

-- unaccent() e STABLE e nao pode ir direto num indice; este wrapper IMMUTABLE permite.
create or replace function public.sem_acento(txt text)
returns text
language sql
immutable
strict
parallel safe
set search_path = ''
as $$ select extensions.unaccent('extensions.unaccent', txt) $$;

-- ────────────────────────────────────────────────────────────────────── tipos

do $$ begin
  create type public.papel_usuario as enum ('OPERADOR','GESTOR');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.tipo_movimentacao as enum ('ENTRADA','SAIDA','AJUSTE');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.motivo_movimentacao as enum (
    'COMPRA','VENDA','DESCARTE','DEVOLUCAO','ESTOQUE_INICIAL','AJUSTE_INVENTARIO');
exception when duplicate_object then null; end $$;

-- ─────────────────────────────────────────────────────────────── atualizado_em

create or replace function public.set_atualizado_em()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.atualizado_em := now();
  return new;
end $$;

-- ────────────────────────────────────────────────────────────────────── tabelas

-- senha_hash: bcrypt custo 12. Nunca retornado pela API.
create table if not exists public.usuarios (
  id            integer generated by default as identity primary key,
  nome          varchar(120) not null,
  email         varchar(180) not null,
  senha_hash    char(60)     not null,
  papel         public.papel_usuario not null default 'OPERADOR',
  ativo         boolean      not null default true,
  criado_em     timestamptz  not null default now(),
  atualizado_em timestamptz  not null default now(),
  constraint uk_usuarios_email              unique (email),
  constraint ck_usuarios_email_minusculo    check (email = lower(email)),
  constraint ck_usuarios_nome_tamanho       check (char_length(nome) between 3 and 120)
);

drop trigger if exists tg_usuarios_atualizado_em on public.usuarios;
create trigger tg_usuarios_atualizado_em before update on public.usuarios
  for each row execute function public.set_atualizado_em();

create table if not exists public.categorias (
  id            integer generated by default as identity primary key,
  nome          varchar(80)  not null,
  descricao     varchar(255),
  ativo         boolean      not null default true,
  criado_em     timestamptz  not null default now(),
  atualizado_em timestamptz  not null default now(),
  constraint uk_categorias_nome unique (nome)
);

drop trigger if exists tg_categorias_atualizado_em on public.categorias;
create trigger tg_categorias_atualizado_em before update on public.categorias
  for each row execute function public.set_atualizado_em();

-- cnpj so digitos, validado na aplicacao. O unique aceita varios NULL,
-- que e o desejado para fornecedor sem CNPJ.
create table if not exists public.fornecedores (
  id            integer generated by default as identity primary key,
  nome          varchar(120) not null,
  cnpj          char(14),
  contato_nome  varchar(120),
  telefone      varchar(20),
  email         varchar(180),
  observacao    varchar(255),
  ativo         boolean      not null default true,
  criado_em     timestamptz  not null default now(),
  atualizado_em timestamptz  not null default now(),
  constraint uk_fornecedores_cnpj unique (cnpj)
);

drop trigger if exists tg_fornecedores_atualizado_em on public.fornecedores;
create trigger tg_fornecedores_atualizado_em before update on public.fornecedores
  for each row execute function public.set_atualizado_em();

-- quantidade_atual e escrita so pelo servico de estoque, dentro de transacao.
-- Os CHECK sao a ultima linha de defesa.
create table if not exists public.produtos (
  id               integer generated by default as identity primary key,
  nome             varchar(150)  not null,
  descricao        varchar(500),
  categoria_id     integer       not null references public.categorias(id)   on delete restrict,
  fornecedor_id    integer                references public.fornecedores(id) on delete restrict,
  preco_venda      numeric(10,2) not null default 0.00,
  quantidade_atual integer       not null default 0,
  estoque_minimo   integer       not null default 0,
  ativo            boolean       not null default true,
  criado_em        timestamptz   not null default now(),
  atualizado_em    timestamptz   not null default now(),
  constraint ck_produtos_qtd_nao_negativa   check (quantidade_atual >= 0),
  constraint ck_produtos_min_nao_negativo   check (estoque_minimo   >= 0),
  constraint ck_produtos_preco_nao_negativo check (preco_venda      >= 0),
  constraint ck_produtos_nome_tamanho       check (char_length(nome) between 2 and 150)
);

drop trigger if exists tg_produtos_atualizado_em on public.produtos;
create trigger tg_produtos_atualizado_em before update on public.produtos
  for each row execute function public.set_atualizado_em();

create index if not exists ix_produtos_ativo_nome       on public.produtos (ativo, nome);
create index if not exists ix_produtos_ativo_categoria  on public.produtos (ativo, categoria_id);
create index if not exists ix_produtos_ativo_fornecedor on public.produtos (ativo, fornecedor_id);
create index if not exists ix_produtos_reposicao        on public.produtos (ativo, quantidade_atual, estoque_minimo);

-- Busca por nome ignorando acento e caixa.
create index if not exists ix_produtos_busca_nome
  on public.produtos (public.sem_acento(lower(nome)) text_pattern_ops) where ativo;

-- Tabela append-only: nunca recebe update nem delete. Correcao se faz com nova linha AJUSTE.
create table if not exists public.movimentacoes (
  id              bigint generated by default as identity primary key,
  produto_id      integer not null references public.produtos(id) on delete restrict,
  usuario_id      integer not null references public.usuarios(id) on delete restrict,
  tipo            public.tipo_movimentacao   not null,
  motivo          public.motivo_movimentacao not null,
  quantidade      integer       not null,
  saldo_anterior  integer       not null,
  saldo_posterior integer       not null,
  preco_unitario  numeric(10,2) not null default 0.00,
  observacao      varchar(255),
  criado_em       timestamptz   not null default now(),
  constraint ck_mov_quantidade check (quantidade >= 0),
  constraint ck_mov_saldos     check (saldo_anterior >= 0 and saldo_posterior >= 0)
);

create index if not exists ix_mov_criado         on public.movimentacoes (criado_em desc);
create index if not exists ix_mov_produto_criado on public.movimentacoes (produto_id, criado_em desc);
create index if not exists ix_mov_usuario_criado on public.movimentacoes (usuario_id, criado_em desc);
create index if not exists ix_mov_relatorio      on public.movimentacoes (tipo, motivo, criado_em);

create or replace function public.bloqueia_alteracao_movimentacao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'movimentacoes e append-only: registre uma nova linha AJUSTE';
end $$;

drop trigger if exists tg_mov_append_only on public.movimentacoes;
create trigger tg_mov_append_only before update or delete on public.movimentacoes
  for each row execute function public.bloqueia_alteracao_movimentacao();

-- Status de estoque nao e coluna: e derivado daqui.
-- O cast para numeric evita a divisao inteira de estoque_minimo / 2.
create or replace function public.status_estoque(quantidade_atual integer, estoque_minimo integer)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select case
    when quantidade_atual = 0                                  then 'SEM_ESTOQUE'
    when estoque_minimo   = 0                                  then 'NORMAL'
    when quantidade_atual <= ceil(estoque_minimo::numeric / 2) then 'CRITICO'
    when quantidade_atual <= estoque_minimo                    then 'BAIXO'
    else 'NORMAL'
  end
$$;

-- Sessoes: tabela do connect-pg-simple. A lib cria sozinha com createTableIfMissing: true.
create table if not exists public."session" (
  sid    varchar      not null collate "default" primary key,
  sess   json         not null,
  expire timestamp(6) not null
);
create index if not exists ix_session_expire on public."session" (expire);

-- ───────────────────────────────────────────────────────────────────────── RLS
-- Toda tabela em public fica exposta pela API PostgREST com a chave anon.
-- A aplicacao acessa o banco por conexao direta, que ignora RLS, entao aqui
-- habilitamos sem policy: nega tudo para anon e authenticated.

alter table public.usuarios      enable row level security;
alter table public.categorias    enable row level security;
alter table public.fornecedores  enable row level security;
alter table public.produtos      enable row level security;
alter table public.movimentacoes enable row level security;
alter table public."session"     enable row level security;

revoke all on public.usuarios, public.categorias, public.fornecedores,
              public.produtos, public.movimentacoes, public."session"
  from anon, authenticated;
